# Generated by Django 4.1.1 on 2022-09-28 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_dataset_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kernel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('use_node_labels', models.BooleanField()),
                ('use_node_attributes', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('values', models.CharField(max_length=200)),
                ('Kernel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.kernel')),
            ],
        ),
    ]
