# Generated by Django 4.1.1 on 2022-09-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_kernel_parameter_kernel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='values',
            field=models.JSONField(),
        ),
    ]
